### ISSUE TITLE
NaN runtime exception

### ISSUE THREAD

**Issue by jfhc** [alexandrebouchard/tips#3]
With this code:

```java
     public double probability(Integer from, Integer to, double time) {
		System.out.println("BD example");
		SimpleBD process = new SimpleBD();
		SimpleBirthDeathPotential potential = new SimpleBirthDeathPotential();
		TimeIntegratedPathSampler<Integer> sampler = new TimeIntegratedPathSampler<Integer>(potential, process);

		sampler.nParticles = 1000000;
		double estimate = sampler.estimateTransitionPr(from, to, time);
		System.out.println("TIPS = " + estimate);
		System.out.println();
		return estimate;
	}

	private class SimpleBD implements tips.Process<Integer> {

		@Override
		public Counter rates(Integer point) {
			Counter<Integer> result = new Counter<Integer>();
			result.setCount(point + 1, birthRate);
			if (point > 0)
				result.setCount(point - 1, deathRate * point);
			return result;

		}

	}

	private class SimpleBirthDeathPotential implements Potential<Integer> {

		public double get(Integer proposed, Integer target) {
			// Just return how far we are from the target.

			return Math.abs(proposed - target);

		}

	}
```

Running
```java
System.out.println(sbd.probability(0,1,20000)); 
```

Results in 

```
BD example
java.lang.RuntimeException: The number 1.0 was expected to be close to NaN (+/- 1.0E-8)
	at bayonet.math.NumericalUtils.checkIsClose(NumericalUtils.java:42)
	at bayonet.math.NumericalUtils.checkIsClose(NumericalUtils.java:47)
	at tips.utils.PotProposal.potPropDistort(PotProposal.java:123)
	at tips.utils.PotProposal.buildPotProposal(PotProposal.java:102)
	at tips.utils.PotProposal.propose(PotProposal.java:77)
	at tips.utils.PotProposal.propose(PotProposal.java:56)
	at tips.TimeIntegratedPathSampler.runTIPS(TimeIntegratedPathSampler.java:218)
	at tips.TimeIntegratedPathSampler.estimateTransitionPr(TimeIntegratedPathSampler.java:178)
	at peterh.SimpleBDNumberModel.probability(SimpleBDNumberModel.java:36)
```

This is with tips 1.0.0 (via Gradle) and Java 8.0_101

**Comment by alexandrebouchard** [comment]
Thanks for the heads up! My hands are tied with the AISTATS deadline right now but will get back to this ASAP. Looking forward to meet in person!

**Comment by alexandrebouchard** [comment]
Finally have some time to look into that. My preliminary suspicion is that the problem comes from the time scale of 20000 selected for the transition probability. One limitation of the method is that it is generally only suitable for cases where the expected number of transitions in the interval is small to moderate. Do you observe similar problems over shorter time scales?
